//
//Types for Errors actions
//
export const GET_ERRORS = "GET_ERRORS";

//
//Types for Project Actions
//

export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";

//
//Types for BACKLOG ACTIONS
//

export const GET_BACKLOG = "GET_BACKLOG";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const ADD_PROJECT_TASK = "ADD_PROJECT_TASK";
export const UPDATE_PROJECT_TASK = "UPDATE_PROJECT_TASK";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";

export const GET_BACKLOG_SUCCESS = "GET_BACKLOG_SUCCESS";
export const GET_PROJECT_TASK_SUCCESS = "GET_PROJECT_TASK_SUCCESS";
export const ADD_PROJECT_TASK_SUCCESS = "ADD_PROJECT_TASK_SUCCESS";
export const UPDATE_PROJECT_TASK_SUCCESS = "UPDATE_PROJECT_TASK_SUCCESS";
export const DELETE_PROJECT_TASK_SUCCESS = "DELETE_PROJECT_TASK_SUCCESS";

//
//Types for BACKLOG ACTIONS
//

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
